apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessor
  labels:
    app: preprocessor
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: preprocessor
  template:
    metadata:
      labels:
        app: preprocessor
    spec:
      containers:
      - name: preprocessor
        image: apache/beam_python3.7_sdk:2.25.0
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["python3 /scripts/preprocessor.py; sleep infinity"]
        env:
            #Modify this to force rolling update of the deployment on config map change.
            - name: CONFIG_HASH 
              value: ""
        volumeMounts:
        - name: preprocessor
          mountPath: /scripts
      volumes:
      - name: preprocessor
        configMap:
          name: preprocessor-script
          defaultMode: 0744