# HDFS CHART CONFIGURATION

# The most relevant values are:
# 
# datanode.nodeCount
# config.hdfsSite.dfs.replication
# 

alpine:
  repository: alpine
  tag: 3.10.2
  imagePullPolicy: IfNotPresent

namenode:
  repository: gchq/hdfs
  tag: 3.2.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  ports:
    http: 9870
    https: 9871
    clientRpc: 8020
    serviceRpc: 8021
    lifelineRpc: 8022
  dataVolumes:
    count: 1
    pvcTemplateSpec:
      storageClassName: null
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

datanode:
  nodeCount: 3
  repository: gchq/hdfs
  tag: 3.2.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  ports:
    http: 9864
    https: 9865
    data: 9866
    ipc: 9867
  dataVolumes:
    count: 1
    pvcTemplateSpec:
      storageClassName: null
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

shell:
  enabled: true
  repository: gchq/hdfs
  tag: 3.2.1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

config:
  path: /etc/hadoop/conf
  coreSite: {}
  hdfsSite:
    dfs.replication: 3
    hadoop.security.authorization: true
    dfs.namenode.datanode.registration.ip-hostname-check: false  # TO AVOID THE "Datanode denied communication with namenode because hostname cannot be resolved" ERROR
  rackAwareness:
    serviceAccountName:
    nodeTopologyLabel: topology.kubernetes.io/zone

secrets:
  path: /etc/hadoop/secrets
  files: {}

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
  host: ""
  # For Traefik:
  # pathPrefix: /hdfs/
  # For Nginx:
  pathPrefix: "/hdfs/(.*)"

postInstallCommands: |-
  hadoop fs -mkdir -p /HeraSDG/raw_data /HeraSDG/clean_data 
  hadoop fs -chown HeraSDG /HeraSDG
  hadoop fs -chmod -R 777 /
  hadoop fs -ls /
