apiVersion: v1
kind: Service
metadata:
  name: my-jupyter-headless-service
spec:
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: my-jupyter-jupyter-0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888 