
# Choose the right Docker image: you can consult alternative images on https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
image:
  repository: "jupyter/pyspark-notebook"
  tag: "latest"

# enable ingress
ingress:
  enabled: true

# disable persistence??
persistence:
  enabled: true
  storageClass:
  accessMode: ReadWriteOnce
  size: 1Gi

#gitNotebooks:
#  secretName: the name of the secret with ssh keys
#  repos:
#    - name: HeraSDG
#      repo: https://github.com/LorenzoPiazza/HeraSDG-BigDataAnalyticsPipeline/notebook
#    - name: grad-git
#      repo: git@github.com:Gradiant/notebooks.git