
# Choose the right Docker image: you can consult alternative images on https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html
image:
  repository: "jupyter/pyspark-notebook"
  tag: "latest"

# enable ingress
ingress:
  enabled: true

# disable persistence??
persistence:
  enabled: true
  storageClass:
  accessMode: ReadWriteOnce
  size: 1Gi


# To clone a repository into the Pod.
# NOTE: It clones the entire repository. So, if needed, it is better to create a "only notebook" repo 
# gitNotebooks:
# #  secretName: the name of the secret with ssh keys
#  repos:
#    - name: HeraSDG
#      repo: git@github.com/LorenzoPiazza/HeraSDG-BigDataAnalyticsPipeline/
  #  - name: grad-git
  #    repo: git@github.com:Gradiant/notebooks.git